baseurl = "http://www.example.com" # Hostname (and path) to the root.
title = "Erick Martin" # Site title.
theme = "coder-portfolio" # Set the theme.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

disqusShortname = "yourdiscussshortname" # Enable or disable Disqus.

[params] # theme parameters
    author = "Erick Martin" # Author's name.
    info = "Environmental Engineer | Full Stack Developer" # Author's job title or info.
    description = "Erick Martin Personal Website" # Site description.
    keywords = "blog,developer,personal" # Site keywords.
    avatarurl = "images/erick-avatar.png" # Contain the path of the optionnal avatar in the static folder.

    footercontent = "Enter a text here." # Add footer content
    fixedbarContent = "Do you want to know me more private?→" # Add fixedbar content
    fixedbarContentAfter = "Thank You! Please share it if you like it→" # Add fixedbar content after click

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    enableTwemoji = true

    # Bottom sns share
    snsShare = true # new add
    # Popular sns share
    # if you want add sns. please message!
    enableTwitterShare = true  # new add
    enableFacebookShare = true # new add
    enableHatenaShare = true   # new add
    enableLineShare = true     # new add
    enableLinkedInShare = true # new add

    thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/erckmartn/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 2
    url = "https://twitter.com/erckmartn/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/erckmartn/"

##
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-sublime"
    weight = 3
    url = "https://www.linkedin.com/in/erckmartn/"
##
# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "posts"
[[menu.main]]
    name = "About"
    weight = 2
    url = "about"




    langseparator = "|" # separates menus from language selectors.

[languages]
    [languages.en]
        languagename = "EN" # The language name to be displayed in the selector.
        title = "Erick Martin"

        # You can configure the theme parameter for each language. 
        [languages.en.params]
        author = "Erick Martin"
        info = "Environmental Engineer | Full Stack Developer"
        description = "Erick Martin personal website"
        keywords = "blog,developer,personal"

        [languages.en.menu] # It is possible to change the menu too.

        [[languages.en.menu.main]]
        name = "About"
        weight = 1.0
        url = "about"

        # [[languages.en.menu.main]]
        # name = "Blog"
        # weight = 2.0
        # url = "posts"

        [[languages.en.menu.main]]
        name = "Projects"
        weight = 3.0
        url = "projects"

        [[languages.en.menu.main]]
        name = "Contact me"
        weight = 4.0
        url = "contact"

    [languages.es]
        languagename = "Es"
        title = "Erick Martin"

        [languages.es.params]
            author = "Erick Martin"
            description = "Erick Martin Website Personalト"
            keywords = "blog,desarrollador, ingenieria ambienal"
            info = "Ingeniero Ambiental | Desarrollador Full Stack"

        [languages.es.menu]

            [[languages.es.menu.main]]
            name = "Sobre mi"
            weight = 1.0
            url = "es/about"

            # [[languages.es.menu.main]]
            # name = "Publicaciones"
            # weight = 2.0
            # url = "es/posts"

            [[languages.es.menu.main]]
            name = "Proyectos"
            weight = 3.0
            url = "es/projects"

            [[languages.es.menu.main]]
            name = "Contacto"
            weight = 4.0
            url = "es/contact"

